Add a `show_progress` argument for `query_solar_system_objects()`
lightkurve/lightkurve pull request #1225
Opened 2022-06-16 03:47 UTC by keyuxing

A `show_progress` argument was added for `query_solar_system_objects()` to control whether to display a progress bar and the urls during the download.

**Before:**
```
>>> lc.query_solar_system_objects()
Querying for SSOs:   0%|                                 | 0/74 [00:00<?, ?it/s]
Downloading http://vo.imcce.fr/webservices/skybot/skybotconesearch_query.php?-mime=text&-ra=247.292944&-dec=78.077754&-bd=0.0875&-loc=C57&EPOCH=2458684.8525856505
|==========================================| 217 /217  (100.00%)         0s
Querying for SSOs:   1%|▎                        | 1/74 [00:03<04:10,  3.44s/it]
Downloading http://vo.imcce.fr/webservices/skybot/skybotconesearch_query.php?-mime=text&-ra=247.292944&-dec=78.077754&-bd=0.0875&-loc=C57&EPOCH=2458684.8539745416
......
Querying for SSOs:  99%|███████████████████████▋| 73/74 [01:09<00:00,  1.05it/s]
Downloading http://vo.imcce.fr/webservices/skybot/skybotconesearch_query.php?-mime=text&-ra=247.292944&-dec=78.077754&-bd=0.0875&-loc=C57&EPOCH=2458709.4124718853
|==========================================| 217 /217  (100.00%)         0s
Querying for SSOs: 100%|████████████████████████| 74/74 [01:10<00:00,  1.05it/s]
>>>
```

**After:**
```
>>> lc.query_solar_system_objects(show_progress=False)
>>>
```

2022-06-16 21:21 UTC, orionlee requested changes
The change looks good.

However, I think the correspond changes in the top-level `LightCurve.query_solar_system_objects()` and `TargetPixelFile.query_solar_system_objects()` appear to be missing. Maybe they are not yet pushed to the PR?

@christinahedges any concern / feedback?

2022-06-16 22:58 UTC, christinahedges commented
Yes I agree with @orionlee totally, great change, we just need to propagate the change to those two functions and then I would say this can be merged. Here are the lines that need updating:

https://github.com/lightkurve/lightkurve/blob/71c4037936578ba0ccd41f387a1def38f1fadb3e/src/lightkurve/targetpixelfile.py#L918

https://github.com/lightkurve/lightkurve/blob/71c4037936578ba0ccd41f387a1def38f1fadb3e/src/lightkurve/lightcurve.py#L1667

2022-06-17 00:52 UTC, keyuxing commented
Oops, I forgot to push the changes in the top-level! Just fixed.

2022-06-17 01:37 UTC, orionlee commented
Thanks! I think this is ready to be merged.

2022-06-17 19:05 UTC, barentsen approved these changes
LGTM.  Thank you @keyuxing! 🙏 

This feature will be part of the upcoming v2.3.0 release.  I will add an entry to the change log after merging.

2022-06-17 19:09 UTC, merged