Add a TargetPixelFile.animate() method powered by `matplotlib.FuncAnimation`
lightkurve/lightkurve pull request #991
Opened 2021-03-02 04:27 UTC by barentsen

This PR proposes to add a matplotlib-based animation method to the TargetPixelFile object.

Screenshot:

<img width="912" alt="Screen Shot 2021-03-01 at 8 25 13 PM" src="https://user-images.githubusercontent.com/817669/109597033-47b6a000-7acc-11eb-8b42-7da7ec661265.png">

2021-03-02 04:28 UTC, barentsen commented
Open question: what is the right name for this feature?
* `tpf.animate()`
* `tpf.plot_animation()`
* `tpf.interact_matplotlib()`
* ...something else... ?

2021-03-02 04:52 UTC, barentsen commented
The suggestion to use matplotlib's FuncAnimation here comes from @christinahedges.

@christinahedges Would you be willing to review?

2021-03-03 18:24 UTC, christinahedges commented
This seems great! Normally I would be hesitant, because we have a lot of this functionality in `tpf.interact`, however, I think there is use for this stand alone, and right now `interact` is quite broken (a bokeh update has made the pixels look funny).

Re name, `tpf.to_animation` might also be good? But `animate` is nice too...i like it.

I need a minute to test out the functionality then I'll review!

2021-03-03 22:18 UTC, christinahedges requested changes
This is a great feature, I think even though it does duplicate some of the features of interact, this is more robust and has a place in lightkurve. I will personally use this a lot! 

I've left some minor comments, but I have no major comments! I'm saying changes because I think there is a typo.

2021-03-03 22:18 UTC, christinahedges commented on src/lightkurve/targetpixelfile.py
> +    def _to_matplotlib_animation(self, step=None, interval=200, **plot_args):
If you are hard coding a default later (`step = 50` perhaps the default should be set up here rather than `None`, `None` steps never makes sense.

2021-03-03 22:18 UTC, christinahedges commented on src/lightkurve/targetpixelfile.py
> +            if step < 1:
I believe this is not indented correctly

2021-03-03 22:18 UTC, christinahedges commented on src/lightkurve/targetpixelfile.py
> +        return HTML(self._to_matplotlib_animation(**plot_args).to_jshtml())
We need a nice error message if we call this from outside an ipython notebook

2021-03-03 22:18 UTC, christinahedges commented on tests/test_targetpixelfile.py
> +    tpf.animate()
Won't this break when we run tests because they aren't being run in ipython?

2021-03-03 22:18 UTC, christinahedges commented on src/lightkurve/targetpixelfile.py
> +    def _to_matplotlib_animation(self, step=None, interval=200, **plot_args):
This function would enable a `to_mp4` method, which might be quite nice.

2021-03-04 21:58 UTC, merged